{ pkgs }: with pkgs; [
  kde-gruvbox
  libsForQt5.accounts-qt
  libsForQt5.akregator
  libsForQt5.ark
  libsForQt5.audiotube
  libsForQt5.applet-window-appmenu
  libsForQt5.applet-window-buttons
  libsForQt5.baloo-widgets
  libsForQt5.bluedevil
  libsForQt5.bluez-qt
  libsForQt5.booth
  libsForQt5.breeze-plymouth
  libsForQt5.breeze-qt5
  libsForQt5.calendarsupport
  libsForQt5.discover
  libsForQt5.dolphin
  libsForQt5.drumstick
  libsForQt5.dxflib
  libsForQt5.eventviews
  libsForQt5.falkon
  libsForQt5.fcitx5-qt
  libsForQt5.filelight
  libsForQt5.flatpak-kcm
  libsForQt5.frameworkintegration
  libsForQt5.full
  libsForQt5.ghostwriter
  libsForQt5.gwenview
  libsForQt5.kaccounts-integration
  libsForQt5.kaccounts-providers
  libsForQt5.kactivities
  libsForQt5.kactivities-stats
  libsForQt5.kactivitymanagerd
  libsForQt5.kaddressbook
  libsForQt5.kalarm
  libsForQt5.kate
  libsForQt5.kcachegrind
  libsForQt5.kcalc
  libsForQt5.kcalendarcore
  libsForQt5.kcharselect
  libsForQt5.kclock
  libsForQt5.kcmutils
  libsForQt5.kcodecs
  libsForQt5.kcoreaddons
  libsForQt5.kdb
  libsForQt5.kdbusaddons
  libsForQt5.kde-cli-tools
  libsForQt5.kde-gtk-config
  libsForQt5.kde-inotify-survey
  libsForQt5.kde2-decoration
  libsForQt5.kdebugsettings
  libsForQt5.kdeconnect-kde
  libsForQt5.kdecoration
  libsForQt5.kdelibs4support
  libsForQt5.kdenetwork-filesharing
  libsForQt5.kdenlive
  libsForQt5.kdeplasma-addons
  libsForQt5.kdesignerplugin
  libsForQt5.kdesu
  libsForQt5.kdev-php
  libsForQt5.kdev-python
  libsForQt5.kdevelop
  libsForQt5.kdevelop-pg-qt
  libsForQt5.kdiagram
  libsForQt5.kdialog
  libsForQt5.kdnssd
  libsForQt5.kdsoap
  libsForQt5.kemoticons
  libsForQt5.kfind
  libsForQt5.kget
  libsForQt5.kglobalaccel
  libsForQt5.kgpg
  libsForQt5.kguiaddons
  libsForQt5.khelpcenter
  libsForQt5.ki18n
  libsForQt5.kiconthemes
  libsForQt5.kidletime
  libsForQt5.kidentitymanagement
  libsForQt5.kimageannotator
  libsForQt5.kimageformats
  libsForQt5.kio
  libsForQt5.kio-admin
  libsForQt5.kio-extras
  libsForQt5.kio-gdrive
  libsForQt5.kipi-plugins
  libsForQt5.kirigami-addons
  libsForQt5.kirigami-gallery
  libsForQt5.kirigami2
  libsForQt5.kjobwidgets
  libsForQt5.kleopatra
  libsForQt5.knotifications
  libsForQt5.knotifyconfig
  libsForQt5.kolourpaint
  libsForQt5.konqueror
  libsForQt5.konsole
  libsForQt5.kontact
  libsForQt5.kontactinterface
  libsForQt5.konversation
  libsForQt5.kopeninghours
  libsForQt5.korganizer
  libsForQt5.kpackage
  libsForQt5.kparts
  libsForQt5.kpeople
  libsForQt5.kpeoplevcard
  libsForQt5.kpimtextedit
  libsForQt5.kpipewire
  libsForQt5.kpmcore
  libsForQt5.kpublictransport
  libsForQt5.krecorder
  libsForQt5.kross
  libsForQt5.kruler
  libsForQt5.krunner
  libsForQt5.krunner-ssh
  libsForQt5.krunner-symbols
  libsForQt5.kscreen
  libsForQt5.kscreenlocker
  libsForQt5.kservice
  libsForQt5.ksshaskpass
  libsForQt5.ksystemlog
  libsForQt5.ksystemstats
  libsForQt5.ktexteditor
  libsForQt5.ktextwidgets
  libsForQt5.ktimer
  libsForQt5.ktnef
  libsForQt5.ktorrent
  libsForQt5.ktrip
  libsForQt5.kunitconversion
  libsForQt5.kuserfeedback
  libsForQt5.kwallet
  libsForQt5.kwallet-pam
  libsForQt5.kwalletmanager
  libsForQt5.kwayland
  libsForQt5.kwayland-integration
  libsForQt5.kweather
  libsForQt5.kweathercore
  libsForQt5.kwidgetsaddons
  libsForQt5.kwin
  libsForQt5.kwin-dynamic-workspaces
  libsForQt5.kwindowsystem
  libsForQt5.lightly
  libsForQt5.layer-shell-qt
  libsForQt5.libdbusmenu
  libsForQt5.libkgapi
  libsForQt5.libksysguard
  libsForQt5.maui-core
  libsForQt5.mauikit
  libsForQt5.mauikit-accounts
  libsForQt5.mauikit-calendar
  libsForQt5.mauikit-documents
  libsForQt5.mauikit-filebrowsing
  libsForQt5.mauikit-imagetools
  libsForQt5.mauikit-terminal
  libsForQt5.mauikit-texteditor
  libsForQt5.mauiman
  libsForQt5.mbox-importer
  libsForQt5.merkuro
  libsForQt5.messagelib
  libsForQt5.milou
  libsForQt5.minuet
  libsForQt5.neochat
  libsForQt5.networkmanager-qt
  libsForQt5.packagekit-qt
  libsForQt5.parachute
  libsForQt5.phonon
  libsForQt5.phonon-backend-gstreamer
  libsForQt5.phonon-backend-vlc
  libsForQt5.pimcommon
  libsForQt5.plasma-applet-virtual-desktop-bar
  libsForQt5.plasma-bigscreen
  libsForQt5.plasma-browser-integration
  libsForQt5.plasma-desktop
  libsForQt5.plasma-disks
  libsForQt5.plasma-framework
  libsForQt5.plasma-integration
  libsForQt5.plasma-nm
  libsForQt5.plasma-pa
  libsForQt5.plasma-sdk
  libsForQt5.plasma-systemmonitor
  libsForQt5.plasma-thunderbolt
  libsForQt5.plasma-vault
  libsForQt5.plasma-welcome
  libsForQt5.plasma-wayland-protocols
  libsForQt5.plasma-workspace
  libsForQt5.plasma-workspace-wallpapers
  libsForQt5.polkit-kde-agent
  libsForQt5.polkit-qt
  libsForQt5.poppler
  libsForQt5.powerdevil
  libsForQt5.print-manager
  libsForQt5.prison
  libsForQt5.qca-qt5
  libsForQt5.qcoro
  libsForQt5.qcsxcad
  libsForQt5.qgpgme
  libsForQt5.qjson
  libsForQt5.qmake
  libsForQt5.qoauth
  libsForQt5.qt3d
  libsForQt5.qt5.qtbase
  libsForQt5.qt5.qtcharts
  libsForQt5.qt5.qtconnectivity
  libsForQt5.qt5.qtdatavis3d
  libsForQt5.qt5.qtdeclarative
  libsForQt5.qt5.qtdoc
  libsForQt5.qt5.qtgamepad
  libsForQt5.qt5.qtgraphicaleffects
  libsForQt5.qt5.qtimageformats
  libsForQt5.qt5.qtlocation
  libsForQt5.qt5.qtlottie
  libsForQt5.qt5.qtmultimedia
  libsForQt5.qt5.qtnetworkauth
  libsForQt5.qt5.qtpositioning
  libsForQt5.qt5.qtquickcontrols
  libsForQt5.qt5.qtquickcontrols2
  libsForQt5.qt5.qtremoteobjects
  libsForQt5.qt5.qtscript
  libsForQt5.qt5.qtscxml
  libsForQt5.qt5.qtsensors
  libsForQt5.qt5.qtserialbus
  libsForQt5.qt5.qtserialport
  libsForQt5.qt5.qtspeech
  libsForQt5.qt5.qtsvg
  libsForQt5.qt5.qtsystems
  libsForQt5.qt5.qttools
  libsForQt5.qt5.qttranslations
  libsForQt5.qt5.qtvirtualkeyboard
  libsForQt5.qt5.qtwayland
  libsForQt5.qt5.qtwebchannel
  libsForQt5.qt5.qtwebengine
  libsForQt5.qt5.qtwebglplugin
  libsForQt5.qt5.qtwebsockets
  libsForQt5.qt5.qtwebview
  libsForQt5.qt5.qtx11extras
  libsForQt5.qt5.qtxmlpatterns
  libsForQt5.qt5.wrapQtAppsHook
  libsForQt5.qtcurve
  libsForQt5.qtdbusextended
  libsForQt5.qtinstaller
  libsForQt5.qtkeychain
  libsForQt5.qtstyleplugin-kvantum
  libsForQt5.qtstyleplugins
  libsForQt5.qtutilities
  libsForQt5.sddm
  libsForQt5.sddm-kcm
  libsForQt5.solid
  libsForQt5.sonnet
  libsForQt5.threadweaver
  libsForQt5.tokodon
  libsForQt5.umbrello
  libsForQt5.xdg-desktop-portal-kde
  libsForQt5.zanshin
]