{ pkgs }:
with pkgs; [
  libsForQt5.accounts-qml-module
  libsForQt5.accounts-qt
  libsForQt5.akonadi
  libsForQt5.akonadi-calendar
  libsForQt5.akonadi-calendar-tools
  libsForQt5.akonadi-contacts
  libsForQt5.akonadi-import-wizard
  libsForQt5.akonadi-mime
  libsForQt5.akonadi-notes
  libsForQt5.akonadi-search
  libsForQt5.akonadiconsole
  libsForQt5.akregator
  libsForQt5.alkimia
  libsForQt5.analitza
  libsForQt5.angelfish
  libsForQt5.appstream-qt
  libsForQt5.arianna
  libsForQt5.ark
  libsForQt5.attica
  libsForQt5.audiotube
  libsForQt5.baloo
  libsForQt5.bluedevil
  libsForQt5.bluez-qt
  libsForQt5.booth
  libsForQt5.bovo
  libsForQt5.buho
  libsForQt5.breeze-plymouth
  libsForQt5.breeze-qt5
  libsForQt5.calendarsupport
  libsForQt5.incidenceeditor
  libsForQt5.clip
  libsForQt5.colord-kde
  libsForQt5.communicator
  libsForQt5.discover
  libsForQt5.dolphin
  libsForQt5.dolphin-plugins
  libsForQt5.drumstick
  libsForQt5.dxflib
  libsForQt5.eventviews
  libsForQt5.fcitx5-qt
  libsForQt5.ffmpegthumbs
  libsForQt5.filelight
  libsForQt5.flatpak-kcm
  libsForQt5.frameworkintegration
  libsForQt5.futuresql
  libsForQt5.ghostwriter
  libsForQt5.grantlee
  libsForQt5.grantleetheme
  libsForQt5.gwenview
  libsForQt5.incidenceeditor
  libsForQt5.index
  libsForQt5.itinerary
  libsForQt5.k3b
  libsForQt5.kaccounts-integration
  libsForQt5.kaccounts-providers
  libsForQt5.kactivities
  libsForQt5.kactivities-stats
  libsForQt5.kactivitymanagerd
  libsForQt5.kalarm
  libsForQt5.kalk
  libsForQt5.kalzium
  libsForQt5.kapidox
  libsForQt5.kapptemplate
  libsForQt5.karchive
  libsForQt5.kasts
  libsForQt5.kate
  libsForQt5.katomic
  libsForQt5.kauth
  libsForQt5.kbookmarks
  libsForQt5.kcachegrind
  libsForQt5.kcalc
  libsForQt5.kcalendarcore
  libsForQt5.kcalutils
  libsForQt5.kcharselect
  libsForQt5.kclock
  libsForQt5.kcmutils
  libsForQt5.kcodecs
  libsForQt5.kcolorchooser
  libsForQt5.kcompletion
  libsForQt5.kconfig
  libsForQt5.kconfigwidgets
  libsForQt5.kcontacts
  libsForQt5.kcoreaddons
  libsForQt5.kcrash
  libsForQt5.kdav
  libsForQt5.kdb
  libsForQt5.kdbusaddons
  libsForQt5.kde-cli-tools
  libsForQt5.kde-inotify-survey
  libsForQt5.kdebugsettings
  libsForQt5.kdeclarative
  libsForQt5.kdeconnect-kde
  libsForQt5.kdecoration
  libsForQt5.kded
  libsForQt5.kdegraphics-mobipocket
  libsForQt5.kdegraphics-thumbnailers
  libsForQt5.kdelibs4support
  libsForQt5.kdenetwork-filesharing
  libsForQt5.kdenlive
  libsForQt5.kdepim-runtime
  libsForQt5.kdepim-addons
  libsForQt5.kdeplasma-addons
  libsForQt5.kdesignerplugin
  libsForQt5.kdesu
  libsForQt5.kdevelop
  libsForQt5.kdf
  libsForQt5.kdiagram
  libsForQt5.kdialog
  libsForQt5.kdnssd
  libsForQt5.kdoctools
  libsForQt5.kdsoap
  libsForQt5.keditbookmarks
  libsForQt5.kemoticons
  libsForQt5.keysmith
  libsForQt5.kfind
  libsForQt5.kf5gpgmepp
  libsForQt5.kfilemetadata
  libsForQt5.kgamma5
  libsForQt5.kget
  libsForQt5.kglobalaccel
  libsForQt5.kgpg
  libsForQt5.kguiaddons
  libsForQt5.khelpcenter
  libsForQt5.kholidays
  libsForQt5.khotkeys
  libsForQt5.khtml
  libsForQt5.ki18n
  libsForQt5.kidentitymanagement
  libsForQt5.kidletime
  libsForQt5.kig
  libsForQt5.kimageannotator
  libsForQt5.kimageformats
  libsForQt5.kimap
  libsForQt5.kinfocenter
  libsForQt5.kinit
  libsForQt5.kio
  libsForQt5.kio-admin
  libsForQt5.kio-extras
  libsForQt5.kio-gdrive
  libsForQt5.kipi-plugins
  libsForQt5.kirigami-addons
  libsForQt5.kirigami2
  libsForQt5.kitemmodels
  libsForQt5.kitemviews
  libsForQt5.kitinerary
  libsForQt5.kjobwidgets
  libsForQt5.kldap
  libsForQt5.kleopatra
  libsForQt5.kmag
  libsForQt5.kmail
  libsForQt5.kmail-account-wizard
  libsForQt5.kmailtransport
  libsForQt5.kmbox
  libsForQt5.kmenuedit
  libsForQt5.kmime
  libsForQt5.kmix
  libsForQt5.kmplot
  libsForQt5.knewstuff
  libsForQt5.knotifications
  libsForQt5.knotifyconfig
  libsForQt5.kompare
  libsForQt5.kongress
  libsForQt5.konqueror
  libsForQt5.konsole
  libsForQt5.kontact
  libsForQt5.kontactinterface
  libsForQt5.konversation
  libsForQt5.kopeninghours
  libsForQt5.korganizer
  libsForQt5.kosmindoormap
  libsForQt5.kpackage
  libsForQt5.kparts
  libsForQt5.kpat
  libsForQt5.kpeople
  libsForQt5.kpeoplevcard
  libsForQt5.kpimtextedit
  libsForQt5.kpipewire
  libsForQt5.kpkpass
  libsForQt5.kplotting
  libsForQt5.kpmcore
  libsForQt5.kproperty
  libsForQt5.kpty
  libsForQt5.kpurpose
  libsForQt5.kqtquickcharts
  libsForQt5.krdc
  libsForQt5.krecorder
  libsForQt5.kross
  libsForQt5.kruler
  libsForQt5.krunner
  libsForQt5.krunner-ssh
  libsForQt5.krunner-symbols
  libsForQt5.ksanecore
  libsForQt5.kscreen
  libsForQt5.kscreenlocker
  libsForQt5.kservice
  libsForQt5.ksmtp
  libsForQt5.ksshaskpass
  libsForQt5.ksystemlog
  libsForQt5.ksystemstats
  libsForQt5.kteatime
  libsForQt5.ktexteditor
  libsForQt5.ktextwidgets
  libsForQt5.ktimer
  libsForQt5.ktnef
  libsForQt5.ktorrent
  libsForQt5.ktouch
  libsForQt5.kunitconversion
  libsForQt5.kwallet
  libsForQt5.kwallet-pam
  libsForQt5.kwalletmanager
  libsForQt5.kwayland
  libsForQt5.kwayland-integration
  libsForQt5.kweather
  libsForQt5.kweathercore
  libsForQt5.kwidgetsaddons
  libsForQt5.kwin
  libsForQt5.kwin-dynamic-workspaces
  libsForQt5.kwindowsystem
  libsForQt5.kwrited
  libsForQt5.kxmlgui
  libsForQt5.kxmlrpcclient
  libsForQt5.kzones
  libsForQt5.layer-shell-qt
  libsForQt5.ldutils
  libsForQt5.libcommuni
  libsForQt5.libdbusmenu
  libsForQt5.libgravatar
  libsForQt5.libkcddb
  libsForQt5.libkdcraw
  libsForQt5.libkdegames
  libsForQt5.libkgapi
  libsForQt5.libkdepim
  libsForQt5.libkexiv2
  libsForQt5.libkipi
  libsForQt5.libkleo
  libsForQt5.libkomparediff2
  libsForQt5.libksane
  libsForQt5.libkscreen
  libsForQt5.libksieve
  libsForQt5.libksysguard
  libsForQt5.libktorrent
  libsForQt5.liblastfm
  libsForQt5.libopenshot
  libsForQt5.libopenshot-audio
  libsForQt5.libqaccessibilityclient
  libsForQt5.libqglviewer
  libsForQt5.libqofono
  libsForQt5.libqtav
  libsForQt5.libquotient
  libsForQt5.lightly
  libsForQt5.mailimporter
  libsForQt5.maplibre-gl-native
  libsForQt5.marble
  libsForQt5.maui-core
  libsForQt5.mauikit
  libsForQt5.mauikit-accounts
  libsForQt5.mauikit-calendar
  libsForQt5.mauikit-documents
  libsForQt5.mauikit-filebrowsing
  libsForQt5.mauikit-imagetools
  libsForQt5.mauikit-terminal
  libsForQt5.mauikit-texteditor
  libsForQt5.mauiman
  libsForQt5.mbox-importer
  libsForQt5.merkuro
  libsForQt5.messagelib
  libsForQt5.milou
  libsForQt5.minuet
  libsForQt5.modemmanager-qt
  libsForQt5.networkmanager-qt
  libsForQt5.okular
  libsForQt5.packagekit-qt
  libsForQt5.parachute
  libsForQt5.partitionmanager
  libsForQt5.phonon
  libsForQt5.phonon-backend-gstreamer
  libsForQt5.phonon-backend-vlc
  libsForQt5.pim-data-exporter
  libsForQt5.pim-sieve-editor
  libsForQt5.pimcommon
  libsForQt5.plasma-applet-virtual-desktop-bar
  libsForQt5.plasma-browser-integration
  libsForQt5.plasma-desktop
  libsForQt5.plasma-dialer
  libsForQt5.plasma-disks
  libsForQt5.plasma-framework
  libsForQt5.plasma-integration
  libsForQt5.plasma-mobile
  libsForQt5.plasma-nano
  libsForQt5.plasma-nm
  libsForQt5.plasma-pa
  libsForQt5.plasma-phonebook
  libsForQt5.plasma-remotecontrollers
  libsForQt5.plasma-sdk
  libsForQt5.plasma-settings
  libsForQt5.plasma-systemmonitor
  libsForQt5.plasma-thunderbolt
  libsForQt5.plasma-vault
  libsForQt5.plasma-welcome
  libsForQt5.plasma-workspace
  libsForQt5.plasma-workspace-wallpapers
  libsForQt5.polkit-kde-agent
  libsForQt5.polkit-qt
  libsForQt5.powerdevil
  libsForQt5.print-manager
  libsForQt5.prison
  libsForQt5.qca
  libsForQt5.pulseaudio-qt
  libsForQt5.qcoro
  libsForQt5.qcsxcad
  libsForQt5.qgpgme
  libsForQt5.qjson
  libsForQt5.qmake
  libsForQt5.qmlkonsole
  libsForQt5.qoauth
  libsForQt5.qqc2-breeze-style
  libsForQt5.qscintilla
  libsForQt5.qt3d
  libsForQt5.qt5.qtbase
  libsForQt5.qt5.qtcharts
  libsForQt5.qt5.qtconnectivity
  libsForQt5.qt5.qtdatavis3d
  libsForQt5.qt5.qtdeclarative
  libsForQt5.qt5.qtdoc
  libsForQt5.qt5.qtgamepad
  libsForQt5.qt5.qtgraphicaleffects
  libsForQt5.qt5.qtimageformats
  libsForQt5.qt5.qtlocation
  libsForQt5.qt5.qtlottie
  libsForQt5.qt5.qtmultimedia
  libsForQt5.qt5.qtnetworkauth
  libsForQt5.qt5.qtpositioning
  libsForQt5.qt5.qtquickcontrols
  libsForQt5.qt5.qtquickcontrols2
  libsForQt5.qt5.qtremoteobjects
  libsForQt5.qt5.qtscript
  libsForQt5.qt5.qtscxml
  libsForQt5.qt5.qtsensors
  libsForQt5.qt5.qtserialbus
  libsForQt5.qt5.qtserialport
  libsForQt5.qt5.qtspeech
  libsForQt5.qt5.qtsvg
  libsForQt5.qt5.qtsystems
  libsForQt5.qt5.qttools
  libsForQt5.qt5.qttranslations
  libsForQt5.qt5.qtvirtualkeyboard
  libsForQt5.qt5.qtwayland
  libsForQt5.qt5.qtwebchannel
  libsForQt5.qt5.qtwebengine
  libsForQt5.qt5.qtwebglplugin
  #libsForQt5.qt5.qtt
  libsForQt5.qt5.qtwebsockets
  libsForQt5.qt5.qtwebview
  libsForQt5.qt5.qtx11extras
  libsForQt5.qt5.qtxmlpatterns
  libsForQt5.qt5.wrapQtAppsHook
  libsForQt5.qt5ct
  libsForQt5.qtmpris
  libsForQt5.qtinstaller
  libsForQt5.qtkeychain
  libsForQt5.qtpbfimageplugin
  libsForQt5.qtstyleplugin-kvantum
  libsForQt5.qtstyleplugins
  libsForQt5.qtutilities
  libsForQt5.qwt
  libsForQt5.qxlsx
  libsForQt5.qzxing
  libsForQt5.rocs
  libsForQt5.sddm
  libsForQt5.sddm-kcm
  libsForQt5.shelf
  libsForQt5.signond
  libsForQt5.skanpage
  libsForQt5.solid
  libsForQt5.sonnet
  libsForQt5.soqt
  libsForQt5.soundkonverter
  libsForQt5.spacebar
  libsForQt5.spectacle
  libsForQt5.syndication
  libsForQt5.syntax-highlighting
  libsForQt5.systemsettings
  libsForQt5.telepathy
  libsForQt5.threadweaver
  libsForQt5.tokodon
  libsForQt5.umbrello
  libsForQt5.yuview
  libsForQt5.xdg-desktop-portal-kde
  libsForQt5.zanshin
  libsForQt5.applet-window-appmenu
  libsForQt5.applet-window-buttons
  libsForQt5.baloo-widgets
  libsForQt5.qtcurve
]
